"""Core data models and utility functions for SDF timing."""

from sdf_toolkit.core.builder import (
    CellBuilder,
    SDFBuilder,
    make_device,
    make_interconnect,
    make_iopath,
    make_path_constraint,
    make_port,
    make_timing_check,
)
from sdf_toolkit.core.model import (
    BaseEntry,
    CellsDict,
    DelayPaths,
    Device,
    EdgeType,
    EntryType,
    Hold,
    Interconnect,
    Iopath,
    PathConstraint,
    Port,
    PortSpec,
    Recovery,
    Removal,
    SDFFile,
    SDFFileValue,
    SDFHeader,
    Setup,
    SetupHold,
    TimingCheck,
    TimingPortSpec,
    Values,
    Width,
)
from sdf_toolkit.core.utils import get_scale_fs, get_scale_seconds

__all__ = [
    # model -- data classes and type aliases
    "BaseEntry",
    "CellsDict",
    "DelayPaths",
    "Device",
    "EdgeType",
    "EntryType",
    "Hold",
    "Interconnect",
    "Iopath",
    "PathConstraint",
    "Port",
    "PortSpec",
    "Recovery",
    "Removal",
    "SDFFile",
    "SDFFileValue",
    "SDFHeader",
    "Setup",
    "SetupHold",
    "TimingCheck",
    "TimingPortSpec",
    "Values",
    "Width",
    # builder
    "CellBuilder",
    "SDFBuilder",
    "make_device",
    "make_interconnect",
    "make_iopath",
    "make_path_constraint",
    "make_port",
    "make_timing_check",
    # utils
    "get_scale_fs",
    "get_scale_seconds",
]
